# Generated by Django 5.2.1 on 2025-06-14 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
