# Generated by Django 5.2.1 on 2025-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_train_arrival_time_alter_train_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='train',
            name='seats_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
