# Generated by Django 5.2.1 on 2025-06-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_booking_time_booking_booking_tim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_tim',
            new_name='booking_time',
        ),
    ]
